name: CI Docker Build & Push

on:
  push:
    branches:
      - main

jobs:
  docker:
   # runs-on: suptech_isi
   runs-on: ubuntu-latest

    #environment: dev

    env:
      IMAGE_NAME: travaildocker
      IMAGE_TAG: 1.0.1
      DOCKER_HUB_REGISTRY: fatouseck98

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4
      
#      - name: Test Varibales
#        run: |
#          echo "Varibale IMAGE_NAME $IMAGE_NAME"
#          echo "Varibale DOCKER_HUB_REGISTRY  $DOCKER_HUB_REGISTRY "

      - name: Connexion à Docker Hub
        #run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login 
           #  -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        uses: docker/login-action@v2
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build de l’image Docker
        run: |
          docker build -t fatouseck98/travaildocker:1.0.1 .
        
      - name: Test de l’image Docker
        run: |
        # docker image ls fatouseck98/travaildocker:1.0.1 
          

      - name: Push de l’image Docker
        run: |
         docker push docker.io/fatouseck98/travaildocker:1.0.1 
